### ISSUE TITLE
(XT and XA tag conflict)Purpose of skipping in function bwa/bwase.c: bwa_aln2seq_core

### ISSUE THREAD

**Issue by Griffan** [lh3/bwa#101]
if we look at this segment of code in bwa_aln2seq_core function:
```
if (set_main) {
		best = aln[0].score;
		for (i = cnt = 0; i < n_aln; ++i) {
			const bwt_aln1_t *p = aln + i;
			if (p->score > best) break;
			if (drand48() * (p->l - p->k + 1 + cnt) > (double)cnt) {
				s->n_mm = p->n_mm; s->n_gapo = p->n_gapo; s->n_gape = p->n_gape;
				s->ref_shift = (int)p->n_del - (int)p->n_ins;
				s->score = p->score;
				s->sa = p->k + (bwtint_t)((p->l - p->k + 1) * drand48());
			}
			cnt += p->l - p->k + 1;
		}
		s->c1 = cnt;
		for (; i < n_aln; ++i) cnt += aln[i].l - aln[i].k + 1;
		s->c2 = cnt - s->c1;
		s->type = s->c1 > 1? BWA_TYPE_REPEAT : BWA_TYPE_UNIQUE;
	}
```
we can see that the s->type, the final XT tag, will be determined by the cnt variable.
What's more, cnt variable is determined by the break in for loop 'if (p->score > best) break;'
This may result in a conflict in final sam records, e.g. when XT report unique hit, but XA may result in several alternative hits. 
Could anyone please enlighten me why do we need this break, what does this part actually doing?
Thanks!

**Comment by lh3** [comment]
XA includes suboptimal hits. `c1` includes best hits only.
