### ISSUE TITLE
BWA not producing output 

### ISSUE THREAD

**Issue by burnsro** [lh3/bwa#105]
I am using  BWA/0.7.15-foss-2016a
We did an strace and it seems to not do anything although it uses 800 % of the CPU. 

I am using the command 
bwa mem -t 8 -U 15 -M -R '@RG\tID:'$acc'\tSM:'$acc'\tPL:Illumina\tLB:'$acc $ref $acc.1.fastq.gz $acc.2.fastq.gz > $out/$acc.sam

where the variables $ref is the reference file
$acc is the sample being mapped
$out is the output directory

The log file only shows
14312
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 800000 sequences (80000000 bp)...
[M::process] read 800000 sequences (80000000 bp)...

I am using 1 node with 16 ncpus and 34GB of memory
and it has been running for more than 1 day now

**Comment by Maryom** [comment]
How did you solve it? I have the same issue
