### ISSUE TITLE
Segmentation fault with specific data set

### ISSUE THREAD

**Issue by tillea** [lh3/bwa#108]
Hi,
I've uploaded an [archive containing a data set](https://people.debian.org/~tille/tmp/bwa/bwa_segmentation_fault.tar.gz) that leads to a segfault when doing
`bwa bwasw -t 20 00-optrApE349.fas 2708-UW15005_S1_L001_R1_001.fastq.gz 2708-UW15005_S1_L001_R2_001.fastq.gz -f test.sam`
The compressed tar archive contains the data set, a script named run_bwa_Segmentation_fault you can simply run to reproduce the issue and the output of the run in the file bwa.out.
I have tested the problem with four versions of bwa (0.7.10, 0.7.14 and 0.7.15) all with the same result and also on two different machines (all running Debian stable, the bwa installation was also from according Debian packages).
Are you able to reproduce the issue and even more importantly fixing it?  As a member of the Debian Med packaging team I'd happily fix the issue in the Debian packaging as soon as there is a fix available.
Kind regards and thanks for providing bwa as Free Software, Andreas.

**Comment by tillea** [comment]
Hi,
do you have any hint about this.  If it helps I can provide another data set with the same problem.
Kind regards, Andreas.

**Comment by lh3** [comment]
Thanks a lot for the example. Yes, I can reproduce the bug (NB: this is a "bwasw" specific bug, not applicable to the more widely used "bwamem"). I will have a look.

**Comment by tillea** [comment]
On Sat, Feb 11, 2017 at 01:49:47PM -0800, Heng Li wrote:
> Thanks a lot for the example. Yes, I can reproduce the bug (NB: this is a "bwasw" specific bug, not applicable to the more widely used "bwamem"). I will have a look.
That's correct, it only appears in bwasw.
Thanks for checking the issue, Andreas.

**Comment by tillea** [comment]
Hi, any news about this?  Sorry for nagging but the issue is in so far urgent as the window to fix the issue inside Debian before the next stable release is nearly closing and a program that segfaults under certain conditions is not good.  Please let me know if I could provide any help.

**Comment by tillea** [comment]
Hi,
may be it helps if I send some gdb output.  I was installing the bwa-dbgsym package for Debian and did run the query above through gdb.  This ended up in

    [bsw2_stat] mean and std.dev: (409.40, 52.50)
    [bsw2_stat] low and high boundaries for proper pairs: (301, 642)
    [bsw2_pair] #fixed=0, #rescued=0, #moved=0
    
    Thread 53 "bwa" received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7ffff38f0700 (LWP 20628)]
    0x000055555557165f in bsw2_pair1 (opt=opt@entry=0x7ffff38efe60, l_pac=l_pac@entry=1968, 
        pac=pac@entry=0x5555557ab960 "\373P%\027\371\017\234\261\301\220(\243\070\003\220\304\003\017\016\271o\307\070\353\f뾀\023k>\003C\214\070\002>sﬀ\350\356\200\004", <incomplete sequence \347>, 
        st=st@entry=0x7ffff38efca0, h=0x7fffc02cba00, l_mseq=149, mseq=<optimized out>, a=<optimized out>, g_mat=<optimized out>) at bwtsw2_pair.c:129
    129     bwtsw2_pair.c: No such file or directory.

Hope this helps tracking down the issue, Andreas.

**Comment by tillea** [comment]
Any news about this issue?  I'd be happy to run some tests if needed.

**Comment by kloetzl** [comment]
A [patch](https://anonscm.debian.org/cgit/debian-med/bwa.git/commit/?id=7722b0f5bb0e2f1d4ceea9ce0f2c6f695969995b) similar to the solution given in PR #141 just landed in Debian.
