### ISSUE TITLE
validity of CIGAR string 

### ISSUE THREAD

**Issue by ngthomas** [lh3/bwa#118]
I have noticed that the CIGAR string column from the SAM output file sometimes does not fully contain the alignment difference between the query sequence and the reference sequence. For example with a sample alignment entry with a CIGAR string of `90M`:
```
SRR2650329.12.indiv_AAA252      83      R36106  686     60      90M     =       30947000        -146    GCTTCTTAACAGCAACTCGCTTAGCCTGGCAGCCAGCTGCACAAATGTGTCAGAGGAAACAGTTAAACTGATGACCAAAGTCAGCCTGCA      >DDDDEDDDCDDDDDDDDEEEEFFFFHHHGJIFJIJJIJIHJJJJJJJJJJJJJJJJJJJJJJIJJIIIJIGIFJJJJJJIJJJIJJHHH      NM:i:2  MD:Z:23A37A28   AS:i:80 XS:i:31
```

Based on the CIGAR string, I expect to see a perfect 90bp perfect match of the query sequence to the reference sequence. Instead, when i compare those two sequences, I have found two omitted substitution:

```
OBS:    GCTTCTTAACAGCAACTCGCTTAGCCTGGCAGCCAGCTGCACAAATGTGTCAGAGGAAACAGTTAAACTGATGACCAAAGTCAGCCTGCA
REF:    GCTTCTTAACAGCAACTCGCTTAACCTGGCAGCCAGCTGCACAAATGTGTCAGAGGAAACAATTAAACTGATGACCAAAGTCAGCCTGCA
NOT:    _______________________*_____________________________________*____________________________
QUA:    >DDDDEDDDCDDDDDDDDEEEEFFFFHHHGJIFJIJJIJIHJJJJJJJJJJJJJJJJJJJJJJIJJIIIJIGIFJJJJJJIJJJIJJHHH
```

obs - as observed; ref - as ref; not - as notation, qua - as phred qual

This is one of the many cases. Was it intentional for bwa not to recognize these base pair substitution event? Both past version (0.7.8) and the latest version (0.7.15) of bwa mem & aln method commit the same type of action.

**Comment by yfarjoun** [comment]
As per the [sam spec](https://samtools.github.io/hts-specs/SAMv1.pdf). The M operator is an **alignment** match, not **sequence** match: 

>    M -- alignment match (can be a sequence match or mismatch)

Some aligners chose to put `=` and `X` operators in the CIGAR (they have the eaning that you want)
