### ISSUE TITLE
bwa mem -T don't work

### ISSUE THREAD

**Issue by zengfengbo** [lh3/bwa#133]
```sh
bwa mem -T 100 -L 30 -t 14 $hg38 $fq1 $fq2 | samtools view -Sb - >  $s.raw.bam
```
why output 

ST-E00206:327:H2LYNALXX:7:2102:5557:23284       147     chr1    952503  40      `17S19M114S `     =       952503  -19     GCTGGTTTATCACTATAGCCAGCAGCTCCGTCAAGGCGTTATCAAGAAAATACACTATCTGCCTTTGGCTTATCTGGATCGGCAGGGAACTGGCGACTTGGTTAGTCGGGTGACGACAGATTTGGAGCAGCTCAGCAATGGCCTACTTAT  <AKKFKKKKKKKKKKKKFKKKKKKFKKKAFAKFAAKFKKFKKKKKKKKKKFKKKFKKFKKFKKKKKKKKKKKKFAKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKFKFKKKKKKKKKKKKKKKKKKKKFFKKKKFFFAA  NM:i:0  MD:Z:19 AS:i:19 XS:i:0

**Comment by zengfengbo** [comment]
it' score only 19.

**Comment by lh3** [comment]
`-T` has no effect on paired-end mapping.
