### ISSUE TITLE
pac2bwtgen: A message mistakenly going to stdout

### ISSUE THREAD

**Issue by karel-brinda** [lh3/bwa#134]
```
$ printf '>\nAAAAAAAAAAAA' > index.fa
$ bwa fa2pac index.fa 2> /dev/null  #ok
$ bwa pac2bwt index.fa index.fa.bwt 2> /dev/null #ok
$ bwa pac2bwtgen index.fa.pac index.fa.bwt 2> /dev/null #not ok
[bwt_gen] Finished constructing BWT in 2 iterations.
```
It is a very minor problem, but it broke one of our unit tests :).

**Comment by lh3** [comment]
bwtgen uses a different algorithm which does not work with short sequences. When you run "bwa index", bwa automatically calls "pac2bwt" for short reference and "pac2bwtgen" for long ones. This is a known issue.

**Comment by karel-brinda** [comment]
@lh3 Thank you for your answer. However, isn't it addressing [this issues](https://github.com/lh3/bwa/issues/119)?

The mini-problem here is that [this line](https://github.com/lh3/bwa/blob/5961611c358e480110793bbf241523a3cfac049b/bwt_gen.c#L1605) prints the text to stdout, not to stderr (like all the other messages of this type). In some of our auxiliary pipelines, this line then arrived to the SAM output, but it was, of course, easy to fix it.

From some reasons very specific to our projects, we need to construct the index step by step. Otherwise we would use the main command (`bwa index`) as you suggest.

**Comment by lh3** [comment]
Oh, I see. Just committed a fix.

**Comment by karel-brinda** [comment]
Thank you.
