### ISSUE TITLE
can't load file from hdfs

### ISSUE THREAD

**Issue by shibuvp** [lh3/bwa#148]
i'm running this command
`./bwa mem -R '@RG\tID:foo\tSM:bar\tLB:library1' hdfs://master.hdp:8020/Data/HumanBase/hg19/hg19.fa hdfs://master.hdp:8020/opt/SampleFastqFile1.fastq  hdfs://master.hdp:8020/opt/SampleFastqFile2.fastq > hdfs://master.hdp:8020/opt/lane.sam`

but getting error, that is failed to load file.
is it possible to load file from hdfs?

thanks!

**Comment by lh3** [comment]
Not supported.
