### ISSUE TITLE
Time taken for processing first chunk of reads in BWA MEM is strangely high

### ISSUE THREAD

**Issue by hasindu2008** [lh3/bwa#157]
While doing some performance tests on BWA MEM with multiple threads, I came across an issue which affects the true speed up with the number of threads.
When I run bwa mem with 64 threads, the processing time for the first 10 chunks is as follows.

[M::mem_process_seqs] Processed 4323256 reads in 15726.306 CPU sec, **692.293** real sec
[M::mem_process_seqs] Processed 4320184 reads in 3135.638 CPU sec, 51.615 real sec
[M::mem_process_seqs] Processed 4320276 reads in 3178.907 CPU sec, 52.582 real sec
[M::mem_process_seqs] Processed 4318024 reads in 3175.632 CPU sec, 54.018 real sec
[M::mem_process_seqs] Processed 4319022 reads in 3172.724 CPU sec, 52.293 real sec
[M::mem_process_seqs] Processed 4318526 reads in 3313.234 CPU sec, 55.521 real sec
[M::mem_process_seqs] Processed 4318932 reads in 3257.607 CPU sec, 53.722 real sec
[M::mem_process_seqs] Processed 4318868 reads in 4152.514 CPU sec, 100.521 real sec
[M::mem_process_seqs] Processed 4319034 reads in 3416.314 CPU sec, 69.923 real sec
[M::mem_process_seqs] Processed 4319384 reads in 3196.003 CPU sec, 53.271 real sec

The first chunk takes about 700 seconds which is only about 50 seconds for the rest of the chunks. Hence, the first chunk takes like 14 times more.  The plot for up to 24 chunks is shown below. The first chunk takes significantly high time.

![image](https://user-images.githubusercontent.com/12987163/31847560-68ed6314-b66a-11e7-96e1-9702c7a61c55.png)

When using 32 threads, the first chunk still takes larger time than the rest, but not as significant as the previous. 
[M::mem_process_seqs] Processed 2162694 reads in 2878.534 CPU sec, **104.214** real sec
[M::mem_process_seqs] Processed 2160564 reads in 2438.712 CPU sec, 78.955 real sec
[M::mem_process_seqs] Processed 2160278 reads in 1824.669 CPU sec, 56.788 real sec
[M::mem_process_seqs] Processed 2159906 reads in 1677.720 CPU sec, 52.189 real sec
[M::mem_process_seqs] Processed 2159982 reads in 1916.059 CPU sec, 59.650 real sec
[M::mem_process_seqs] Processed 2160294 reads in 1834.537 CPU sec, 57.030 real sec
[M::mem_process_seqs] Processed 2159190 reads in 1698.318 CPU sec, 52.723 real sec
[M::mem_process_seqs] Processed 2158836 reads in 1980.733 CPU sec, 62.319 real sec
[M::mem_process_seqs] Processed 2159350 reads in 1789.870 CPU sec, 55.717 real sec
[M::mem_process_seqs] Processed 2159672 reads in 1807.541 CPU sec, 56.499 real sec
![image](https://user-images.githubusercontent.com/12987163/31847566-7c243d9a-b66a-11e7-8030-0790c7b5b18b.png)

When using 16 threads it becomes further less significant. 
M::mem_process_seqs] Processed 1081892 reads in 1218.017 CPU sec, 82.443 real sec
[M::mem_process_seqs] Processed 1080804 reads in 725.574 CPU sec, 45.114 real sec
[M::mem_process_seqs] Processed 1080026 reads in 801.271 CPU sec, 50.020 real sec
[M::mem_process_seqs] Processed 1080538 reads in 1249.180 CPU sec, 81.328 real sec
[M::mem_process_seqs] Processed 1080306 reads in 830.485 CPU sec, 51.697 real sec
[M::mem_process_seqs] Processed 1079974 reads in 671.136 CPU sec, 41.536 real sec
[M::mem_process_seqs] Processed 1080062 reads in 652.531 CPU sec, 40.505 real sec
[M::mem_process_seqs] Processed 1079846 reads in 706.295 CPU sec, 44.154 real sec
[M::mem_process_seqs] Processed 1080004 reads in 729.847 CPU sec, 45.864 real sec
[M::mem_process_seqs] Processed 1079980 reads in 744.272 CPU sec, 47.868 real sec
![image](https://user-images.githubusercontent.com/12987163/31847574-8eadcbc0-b66a-11e7-9f0f-28b729406599.png)

What is the reason for this unusual behaviour? I believe this is a bit of issue when comparing the performance of BWA MEM with other tools and how performance scales up in BWA MEM with the number of threads.  For instance, see the following charts that show up the processing time for different data set sizes.
![image](https://user-images.githubusercontent.com/12987163/31847582-b730c278-b66a-11e7-886d-33dbaea38e76.png)
![image](https://user-images.githubusercontent.com/12987163/31847590-bfac95b2-b66a-11e7-9989-f6729ca9248f.png)
![image](https://user-images.githubusercontent.com/12987163/31847598-c606c8ce-b66a-11e7-8cec-8e15ad08b459.png)

Due to the issue with the first chunk, when using a dataset of 4M gives the impression that BWA MEM slows down after 32 threads.   At 100M, the effect of the first chunk is reduced, but the speed up at 64 threads is still low. At about 400M reads only, the effect seems to get fully hidden due to many chunks. Here we see a speed up closer to 2 times at 64 threads.
I have seen some places that compare the performance of aligners using small data sets as 1M reads. The above strange issue might give the impression that leads to thinking that the speedup does not scale up beyond 32 threads. Further, a couple of my friends were taking some performance results using 1M reads that lead to some false speed ups and hypothesis, until this issue was accidentally found.

The data set which I used for the above tests are from https://www.garvan.org.au/research/kinghorn-centre-for-clinical-genomics/clinical-genomics/sequencing-services/sample-data (replicate 1  - R1 reads) where I extracted the 4M, 100M and 400M reads from them.  I have tried on few other simulated data sets as well, where I can replicate the same timing anomaly. The computer used for performance tests has 4 Intel Xeon CPU X7560  @ 2.27GHz (total of 32 cores/64 threads) processors and 256GB of RAM. Unfortunately, I do not have access to another computer with more than 32 threads and hence do not know whether this behaviour is only on this computer. BWA version  0.7.15-r1140 was used.

The log files for 100M data are attached.
[16threads.txt](https://github.com/lh3/bwa/files/1403739/16threads.txt)
[32threads.txt](https://github.com/lh3/bwa/files/1403740/32threads.txt)
[64threads.txt](https://github.com/lh3/bwa/files/1403741/64threads.txt)

**Comment by lh3** [comment]
bwa-mem is not optimized for multi-threading with many cores. I guess for the first batch, malloc is building up the heap space, which is costly. The following batches mainly reuse the heap obtained from the first batch, so they are faster. To confirm if this is the case, you can replace the default linux allocator with [tcmalloc](http://goog-perftools.sourceforge.net/doc/tcmalloc.html) or [lockless allocator](http://locklessinc.com/downloads/) by running bwa-mem with:
```sh
LD_PRELOAD=/path/to/libtcmalloc.so bwa mem ...
```
If my guess is correct, this will alleviate the problem. You will also see bwa-mem use less system time.

**Comment by hasindu2008** [comment]
Yes, that guess is exactly correct. When I run with libtcmalloc for 64 threads, now I get,

[M::mem_process_seqs] Processed 4323256 reads in 3991.354 CPU sec, **65.861** real sec
[M::mem_process_seqs] Processed 4320184 reads in 3052.267 CPU sec, 50.756 real sec
[M::mem_process_seqs] Processed 4320276 reads in 3047.244 CPU sec, 50.956 real sec
[M::mem_process_seqs] Processed 4318024 reads in 3107.342 CPU sec, 51.993 real sec
[M::mem_process_seqs] Processed 4319022 reads in 2898.066 CPU sec, 48.667 real sec
[M::mem_process_seqs] Processed 4318526 reads in 3139.701 CPU sec, 52.879 real sec
[M::mem_process_seqs] Processed 4318932 reads in 3031.550 CPU sec, 51.130 real sec
[M::mem_process_seqs] Processed 4318868 reads in 2945.167 CPU sec, 50.539 real sec
[M::mem_process_seqs] Processed 4319034 reads in 3075.201 CPU sec, 52.539 real sec
[M::mem_process_seqs] Processed 4319384 reads in 2969.848 CPU sec, 50.065 real sec

The first batch which was 692 seconds is now just 66 secons. 

In addition now the speed up is visible even for the small 4M data set.
![image](https://user-images.githubusercontent.com/12987163/31851773-8405d2b4-b6b8-11e7-8465-a16821040e97.png)

**Comment by lh3** [comment]
Thanks for the confirmation. This has been a known issue for a long time, but it would require a lot of code changes to fix. I will leave this to tcmalloc.
