### ISSUE TITLE
bwa mem: Passing a variable to read group

### ISSUE THREAD

**Issue by royfrancis** [lh3/bwa#158]
I would like to add read group info (`-R`) during the mapping/alignment stage.

I am doing something like this:
```
bwa mem \
-M \
-t 8 \
-v 3 \
-R <(sh a-illumina-read-group.sh $1) \
"$path_dr_bwaindex_genome" \
$1 $2
```

where the read group string is generated automatically from the fastq file by the shell script `a-illumina-read-group.sh`. It produces a string like: 

`'@RG\tID:ST-E00215_230_HJ3FMALXX_2\tSM:ST-E00215_230_HJ3FMALXX_2_ATCACG\tLB:ATCACG\tPL:ILLUMINA'`

but, when I run bwa, it fails with this error:
`[E::bwa_set_rg] the read group line is not started with @RG`

I have tried excluding the single quotes (`''`) around read group info, but that didn't change anything. I also tried variations in how the variable is passed.

`-R=$(sh a-illumina-read-group.sh $1) \`
`-R=$(echo $(sh a-illumina-read-group.sh $1)) \`

But, they all produce the same error. I would appreciate any solutions to this issue.
Thanks.

**Comment by hjjansen** [comment]
Ran into the same issue, looked in the code of bwa.c and found
`if (bwa_verbose >= 1) fprintf(stderr, "[E::%s] the read group line contained literal <tab> characters -- replace with escaped tabs: \\t\n", __func__);`
Replaced my \t for \\t and it worked

**Comment by royfrancis** [comment]
I eventually got it to work. This is what worked for me:

```sh
#!/bin/bash

header=$(zcat $1 | head -n 1)
id=$(echo $header | head -n 1 | cut -f 1-4 -d":" | sed 's/@//' | sed 's/:/_/g')
sm=$(echo $header | head -n 1 | grep -Eo "[ATGCN]+$")
echo "Read Group @RG\tID:$id\tSM:$id"_"$sm\tLB:$id"_"$sm\tPL:ILLUMINA"

bwa mem \
-M \
-t 8 \
-v 3 \
-R $(echo "@RG\tID:$id\tSM:$id"_"$sm\tLB:$id"_"$sm\tPL:ILLUMINA") \
"$path_bwaindex_genome" \
$1 $2
```

where the incoming `$1` and `$2` are paired-end fastq files.

**Comment by harrison-anth** [comment]
Thanks to everyone for writing about this issue. Not too sure if this will be applicable for anyone else, but this part of your code:
> where the incoming `$1` and `$2` are paired-end fastq files.
for some reason does not run on my cluster. Replacing $1 and $2 with $one and #two works fine though. Just in case anyone is having trouble. Might be a slurm based thing..
