### ISSUE TITLE
Should -x ont2d be used with all nanopore samples or only 2d reads?

### ISSUE THREAD

**Issue by arfesta** [lh3/bwa#161]
Not sure where to post this question ... but I'm curious if the -x ont2d flag would be OK if the nanopore reads are 1D?

**Comment by lh3** [comment]
Yes, it should be ok if you use relatively recent chemistry. BTW, it is recommended to use [minimap2](https://github.com/lh3/minimap2) for pacbio and nanopore reads. The long-read alignment part of bwa-mem won't receive improvements in future.
