### ISSUE TITLE
-M option query

### ISSUE THREAD

**Issue by prasundutta87** [lh3/bwa#163]
I am using BWA mem (0.7.17-r1188). If I use -M (mark shorter split hits as secondary) so that I can run the resulting BAM file through picard markduplicates, how will it effect actual supplementary alignments that resulted though translocations/INDELS etc? Should I use it in conjunction with -q for this issue?

**Comment by lh3** [comment]
No need to add -M if you are using recent picard.

**Comment by prasundutta87** [comment]
Thank you for the quick reply. I already generated the alignments with -M option. Will it affect my downstream result now during de-duplication? And I believe I lost my supplementary read information now as well.

There is a lot of old documentation floating around with outdated information that comes up in the search results.
