### ISSUE TITLE
mapping quality table

### ISSUE THREAD

**Issue by prasundutta87** [lh3/bwa#164]
Is there a mapping quality table that is mentioned anywhere that BWA mem is following? Like mapping quality if the match has been found only in one place or two places, or three places and henceforth? Again, this question arises as people discussing this is spread across the internet and I want to know what the newest release (0.7.17-r1188) follows.

**Comment by lh3** [comment]
There is no simple equation. The closest is [this one](https://bioinformatics.stackexchange.com/questions/2417/meaning-of-bwa-mem-mapq-scores/2469#2469).
