### ISSUE TITLE
Trace Back Pointers in Smith Waterman

### ISSUE THREAD

**Issue by vijay4454** [lh3/bwa#166]
Hello

I have recently started looking into sequence alignment algorithms in general and bwa-mem in particular. I have a basic question about the ksw_extend2 function in ksw.c in the bwa-mem codebase. At the outset, I must admit that I have a somewhat abstract understanding of the codebase and the ksw_extend2. 

Now, as I understand, the ksw_extend2 applies seed extension using smith-waterman algorithm. In standard smith waterman, trace back pointers need to be computed in order to trace back the best matching path in the matrix. But I do not see any trace back pointers being computed in ksw_extend2 (or perhaps it is being computed and I do not understand which variable represents the trace back pointer)? Are these being computed somewhere else in the code?

Thanks in Advance
Vijay

**Comment by lh3** [comment]
Traceback is done by `ksw_global()` at the end, not by `ksw_extend2`.
