### ISSUE TITLE
[E::bwa_set_rg] the read group line is not started with @RG

### ISSUE THREAD

**Issue by jgarces02** [lh3/bwa#174]
Hi, 

I'm a bit naïve with BWA so maybe it's a silly thing but anything seems tto work... I'm running this following command:
```
RG_header="'@RG\tID:123\tCN:Home\tLB:SureSelect\tPL:Illumina\tSM:123'"
bwa mem -t 20 -R $RG_header $ref 123_1P.fastq.gz 123_2P.fastq.gz 
```
*(Double quotes make that $RG_header is inside other simple quotes.)
And it prompt this error: `[E::bwa_set_rg] the read group line is not started with @RG`.  Without quotes (either double, simple or neither), this another appears: `[E::bwa_set_rg] no ID within the read group line` (according the help, it should be flanked by simple quotes: `-R STR        read group header line such as '@RG\tID:foo\tSM:bar' [null]`).

I'm a bit desperate, any suggestion, please??

**Comment by lh3** [comment]
You can run:
```sh
export RG_header="'@RG\tID:123\tCN:Home\tLB:SureSelect\tPL:Illumina\tSM:123'"
echo $RG_header
```
You will see:
```
'@RG\tID:123\tCN:Home\tLB:SureSelect\tPL:Illumina\tSM:123'
```
The problem is that this string starts with a single quotation mark, not '@'. You should just remove double quotation marks in your comment line:
```sh
RG_header='@RG\tID:123\tCN:Home\tLB:SureSelect\tPL:Illumina\tSM:123'
bwa mem -t 20 -R $RG_header $ref 123_1P.fastq.gz 123_2P.fastq.gz 
```
