### ISSUE TITLE
Decompress .bwt file and .sa file

### ISSUE THREAD

**Issue by Maryom** [lh3/bwa#178]
Hi,

Thanks for your efforts.

I have a question if you don't mind.

After indexing I got files. I need to use .bwt file and .sa file in my algorithm.

My question is: is there a way to decompress .bwt file and .sa file ?

I tried `zlib.decompress` it doesn't work.

Any help will be appreciated.

**Comment by Maryom** [comment]
Or how can I use them while they are compressed?!

**Comment by Maryom** [comment]
The naive way of generating these file is:  

1. Create all rotations of T
2. Sort the rotations lexicographically
3. Concatenate the last character of each rotation to form  BWT(T)

I used this naive way in my algorithm. The problem is it took too much memory.

My question is: is there an effective memory way to generate .bwt file and .sa file ?

**Comment by lh3** [comment]
At least read the bwa paper first.

**Comment by Maryom** [comment]
I’m sorry if my question is not that good ..
I read this paper:
https://academic.oup.com/bioinformatics/article/25/14/1754/225615

And I tried to find a solution to my question and I didn’t find, maybe I missed something. There is no problem in asking others to learn from each other.
If you don’t mind: could you please guide me where can I find a solution to my question?

**Comment by Maryom** [comment]
@lh3 My question in other words is did you store all rotations in memory then sort them lexicographically ? This storing even though it’s temporary it took too much memory! So did compressed them to save memory? Then how you sort them while they are compressed?!

**Comment by lh3** [comment]
How to construct BWT efficiently is a big topic in computer science. No one uses the original BWT definition in practice. The BWA paper gives you the pointer in section 2.2: Hon et al (2007). You should follow the literature.

In practice, you can use existing libraries like libdivsufsort and sais. They consume quite a lot of memory, but that should not be too bad nowadays. Or you can use bwa/bwt.c to read .bwt and .sa. You need to read the source code. Several other developers have done that.

**Comment by Maryom** [comment]
This is exactly what I need to know. Thank you so much.
