### ISSUE TITLE
fail to locate the index files

### ISSUE THREAD

**Issue by haidudu** [lh3/bwa#182]
hallo
this is my command:
nohup /biosoft/bwa/bwa mem /data3/haidu/Botrytis_cinerea_B05.10_genome.fa BCKY_S27_L002_R1_001_paired.fq.gz BCKY_S27_L002_R2_001_paired.fq.gz > huangbwa.sam &

then it turned: [E::bwa_idx_load_from_disk] fail to locate the index files
i don't know the reason

thanks

**Comment by lh3** [comment]
You need to run "bwa index" first.
