### ISSUE TITLE
argument order

### ISSUE THREAD

**Issue by outpaddling** [lh3/bwa#195]
Do you support placing file arguments before flags?
ddocent generates bwa commands like the following:
`bwa mem reference.fasta PopB_19.R1.fq.gz PopB_19.R2.fq.gz -L 20,5 -I 200,40,300,100 -t 8 -a -M -T 10 -A 1 -B 4 -O 6 -R '@RG\tID:PopB_19\tSM:PopB_19\tPL:Illumina'`
GNU getopt() tolerates this and skips forward to the -L, but BSD getopt() returns -1 for the first argument encountered (reference.fasta).
I can either patch bwa to work with BSD getopt() or patch ddocent to put the file arguments after the flags.   Which would you suggest?

**Comment by jmarshall** [comment]
Patch dDocent. There is no reason for a big script like that to depend on this non-portable GNU getopt() behaviour.

**Comment by outpaddling** [comment]
Already did so in the port framework.  I'll see if they will accept the patch upstream.
