### ISSUE TITLE
Mapping quality cap

### ISSUE THREAD

**Issue by dancooke** [lh3/bwa#213]
Hi Heng,

BWA caps the mapping quality at 60.

Some variant callers (including [octopus](https://github.com/luntergroup/octopus)) use mapping quality as part of the read likelihood calculation, essentially by capping read likelihoods. For short read Illumana-quality data this is fine as the contribution of error qualities will almost always be below the cap imposed by the mapping quality cap. But for longer, noisier, reads the errors can easily add up so that the cap is reached. This leads to reads coming from distinct haplotypes having the same likelihood simply because they all reached the cap imposed by the mapping quality due to read errors, which makes variant calling problematic.

I can see why a mapping quality cap of 60 might make sense for very short reads, but for longer reads I'm not so sure. Is there some justification behind this?

Would it make sense to have BWA-MEM automatically adjust the mapping quality cap based on the read length? Otherwise, could the mapping quality cap be made into a command line option?

Thanks,
Dan

**Comment by ekg** [comment]
It is difficult to validate through simulation that the mapping quality calculation is appropriate above Q 60 (requiring 1M reads per error). In practice simulations require many times this number of reads in order to establish the significance of the MQ. As I understand from my own work on an aligner, this is the justification for the cap. Yes, a higher range may provide useful information, but what is the meaning of a Q 120 mapping quality? We'll never be able to meaningful verify that this is an accurate estimate.

It would be better to deal with this at the level of the variant caller.

Ultimately MQ is mostly dependent on the first and second best mappings for the read. By retaining this it is also possible to develop your own MQ calculation downstream.

**Comment by dancooke** [comment]
Thanks for the input Erik.

I agree the precise meaning of mapping quality is far from clear-cut, stemming from "correctly mapped" being ill-defined. However, I think qualitatively the meaning is quite clear: should the mapping be trusted? It seems intuitive to me that the uncertainty in mapping increases with a bigger reference and decreases with a longer read length. Clearly as the read length approached the genome size - which they now are - the mapping quality should tend towards infinity (at least considering a linear reference). I'm not sure we really need a precise definition in order to benefit from a full range of qualities, so long as the resulting inferences are useful, and I think the people best placed to assign the remaining range are those designing mappers not variant callers. At least everyone will then be using the same poorly defined value, which I think is a better alternative to having everyone doing their own thing downstream of mapping. Those downstream can still opt to cap mapping quality if they choose to, but it's much more difficult to go the other way.

**Comment by lh3** [comment]
In practice, you can hardly get mapQ>=60 regardless of read lengths. This is limited by errors in the reference genome. An attempt to artificially increase mapping quality is not right.

> But for longer, noisier, reads the errors can easily add up so that the cap is reached. This leads to reads coming from distinct haplotypes having the same likelihood simply because they all reached the cap imposed by the mapping quality due to read errors, which makes variant calling problematic.

I don't understand. In GATK/samtools, the opposite is true: the mapQ cap never matters for noisy reads. You must be using mapQ cap differently.

**Comment by dancooke** [comment]
> In practice, you can hardly get mapQ>=60 regardless of read lengths. This is limited by errors in the reference genome.

Not sure I understand this. Surely mapping quality depends only on the reference itself, not on some unknown genome it approximates?

> I don't understand. In GATK/samtools, the opposite is true: the mapQ cap never matters for noisy reads. You must be using mapQ cap differently.

Octopus (optionally) uses the following likelihood calculation:

```
p(read | haplotype) = p(read missmapped) p(read | haplotype, read missmapped)
                      + p(read correctly mapped) p(read | haplotype, read correctly mapped)
                    ~= p(read correctly mapped) p(read | haplotype, read correctly mapped)
                      + p(read missmapped)
```

where the second line follows by assuming `p(read | haplotype, read  missmapped) = 1`. Hence we get a soft max induced by the mapping quality `p(read missmapped)`. Now suppose a read has many errors to the point they reduce the likelihood beyond `p(read missmapped)`. Then a haplotype that contains the variant will have essentially equal likelihood (the cap) to one that doesn't, so they can't be distinguished. This becomes more probable as the read length increases.

> An attempt to artificially increase mapping quality is not right.

What do you mean by artificial? Ultimately mapping quality is not particularly well defined as it is, but it turns out to be useful. If we can improve downstream inferences by providing more poorly defined quantities then that seems like a good thing to me. So long as it is clear that is what we're doing.

**Comment by dancooke** [comment]
> You need to artificially change this because the following is wrong:
>
>> where the second line follows by assuming p(read | haplotype, read missmapped) = 1
>
> If the read gets mismapped, it has to be originated from another true haplotype and the probability of generating the read from that true haplotype is definitely not 1.

Yes, all models are wrong, but this is a useful approximation that gives good results in practice. It may not even be that unreasonable considering, as you said, if the read is not mapped then it could potentially have originated from anywhere.

> It is artificial because in reality, you can't achieve an error rate below 1e-6.

It could well be my poor understanding, but I'm not convinced an "error" has been fully defined. The MAQ paper defines mapping quality in terms of the alignment being wrong, but then what do we mean by "wrong" here? You say the read may "come" from a sequence not in the reference, but if we take this literally (i.e. identical by origin) then all mappings will be wrong with probability one, unless we are sequencing reference material. If we say we mean "comes from" in the sense of coming from an IBD sequence then how can we then talk about the read coming from contamination? This definition would be oblivious to that.

I can understand how you might arrive at an minimum "error rate" from simulation, but this would appear to come with a bunch of other assumptions that may not reflect reality. You say that errors in the reference contribute to the cap, but presumably you're referring to the human reference, what about other references? If I generate a read that spans the entire genome of my sample then I do not accept there is a 1e-6 probability of it being wrong, whichever way we define "wrong".

Ultimately, mapping quality is clearly a very useful value, but I question the logic in assigning a fairly arbitrary cap. I'm not convinced this isn't throwing away useful information. Surely the best test of what range of mapping qualities are useful should be the results we get from downstream inferences? If we can get better variant calls from having a wider range of mapping qualities then I don't see the sense in not doing so out of principle.

Maybe an optional command line parameter? :)

**Comment by lh3** [comment]
> Yes, all models are wrong, but this is a useful approximation that gives good results in practice.

Your assumption basically means: once a read is mismapped, it has no sequencing errors. That is wrong. No matter what the true haplotype is, the probability of generating a nanopore read is far below 1, something like `\prod_i (1-10^{-q_i/10})`, where `q_i` is the base quality.

> what do we mean by "wrong" here

"Wrong" means the original read region in the sample is not orthologous to the mapped reference region. This is also how we evaluate cross-species alignments for ages.

> an optional command line parameter?

I am not adding a parameter because you insist on a wrong model. This thread is concluded. I am closing this now.

**Comment by lh3** [comment]
> something like \prod_i (1-10^{-q_i/10}), where q_i is the base quality.

Actually, should even be far below this value because the formula above still assumes the read has no errors.
