### ISSUE TITLE
softclipping query

### ISSUE THREAD

**Issue by prasundutta87** [lh3/bwa#214]
Hi,

I was wondering if soft clipping has any relation to the MAPQ given to a particular read. For example, if a read of 250 bp is soft-clipped so that 200 bases aligns to a genomic region, will it get a higher MAPQ than the read, if 100 bases are soft-clipped so that 150 bases align.

**Comment by lh3** [comment]
The mapQ of a secondary alignments is capped by the mapQ of the corresponding primary alignment.

**Comment by prasundutta87** [comment]
Thank you!
