### ISSUE TITLE
k == 0 causes out-of-bound access

### ISSUE THREAD

**Issue by ycgasjy** [lh3/bwa#217]
In this line https://github.com/lh3/bwa/blob/5961611c358e480110793bbf241523a3cfac049b/bwt.c#L173
k == 0 will cause out of bound access
and check k==(bwtint_t)(-1) is meaningless because bwtint_t is a uint64_t, -1 will be converted to 0xffffffffffffffff, this condition will never happen

**Comment by lh3** [comment]
> this condition will never happen

That happens when you pass k=-1 to the function.

> k == 0 will cause out of bound access

That won't happen.
