### ISSUE TITLE
How to create .alt index file?

### ISSUE THREAD

**Issue by patelhardip** [lh3/bwa#231]
Hi
We have generated whole genome assemblies from multiple individuals and identified regions of the genome with alternate haplotypes. Currently bwa seems to use `.alt` file during the indexing and mapping step to assign reads to primary assembly where possible using the mapping of alternate contigs represented in `.alt` file.

We would like to generate `.alt` representation of alternate haplotypes (contigs) as in .alt. I have following questions to understand the process of generating `.alt` file for use in mapping and indexing.

I have attempted to recreate the `.alt` record for a sequence with ID `chr6_KI270802v1_alt` in hs38da. 

GATK resource bundle for hg38 as a `.alt` file with the following information for sequence ID `chr6_KI270802v1_alt`

```
chr6_KI270802v1_alt	0	chr6	166220580	255	42042M1D10112M1I733M5D2858M4D3668M1I3177M206D2126M1217I469M8601S	*	0	0	*	*	NM:i:1478
```

I used minimap2 to map `chr6_KI270802v1_alt` against `chr6` sequence and I get the following output.

```
chr6_KI270802v1_alt	0	chr6	166220580	60	42042M1D10112M1I733M3D22M2D2836M4D3668M1I3020M206D2283M10287S	*	0	0	*	*	NM:i:253
```

As you can notice, cigar strings and the values of mismatches are different between the two; 1478 in `.alt` file vs 253 in minimap2 output.

I was wondering if this difference has any **serious** consequence especially for the cigar operations used for transferring mapping information from alt-contigs to primary assembly.

**Is there a documentation that I can refer to for generating `.alt` file?** It would be useful not only for human genome analyses but other species too. I am happy to contribute to this documentation if I can get an understanding of how and what information in `.alt` file is used during indexing and mapping.

Cheers

**Comment by lh3** [comment]
There was no minimap2 when this GRCh38 .alt file was generated. The alignments there were provided by GRC with some manual curation as I remember. I would use minimap2 to generate .alt files these days.

**Comment by patelhardip** [comment]
If I use minimap2 to generate the .alt file, would it be possible to use the output of minimap2 (as above for example) in the .alt file?
Would the differences between current .alt file and minimap2 output lead to any serious side effects (please see above for the differences)?
Cheers

**Comment by lh3** [comment]
> If I use minimap2 to generate the .alt file, would it be possible to use the output of minimap2 (as above for example) in the .alt file?

You can. And you don't need the sequence column in SAM. I would probably use larger "-r7k" to generate more contiguous alignment.

> Would the differences between current .alt file and minimap2 output lead to any serious side effects (please see above for the differences)?

I don't know. I think the difference should be minor. Minimap2 may also be doing a better job than older aligners.

**Comment by patelhardip** [comment]
Thank you so much for this. This is great help.

**Comment by gillianmeeks** [comment]
Hi @hp2048, 
I am trying to create my own custom alt index file with the output of minimap2.  Did you figure out how to convert the output of minimap2 into the format required for alt index files? Thanks

**Comment by hp2048** [comment]
@gillianmeeks: Unfortunately I didn't pursue this further at the time. However, all I did in the example above was use the SAM output of minimap2 and replaced `sequence` field with `*` to create `.alt` looking string. Following code should be able do that.

```
minimap2 -a -Y -N 50 --secondary=no -x asm5 -r7k -o output.sam ref.fasta altseq.fa
samtools view -F 256 output.sam | \
perl -lne '$_ =~ /(NM:i:\d+)/; $nmtag=$1; @a=split("\t",$_); $a[9] = "*"; \
print join("\t",@a[0..10])."\t$nmtag";' >ref.fasta.alt
```

Caveats: I am not sure how soft-clip, supplementary alignments, mapping quality values and mapping strand are handled downstream in `postalt.js`. Perhaps @lh3 or someone can clarify this. Hope this is useful.

**Comment by gillianmeeks** [comment]
Thanks so @hp2048 . That was very helpful. I'm specifically trying to make an alt index file for an HLA contig. @lh3 Would ending the index entry after the NM tag provide sufficient information for the alt index?

**Comment by hp2048** [comment]
@gillianmeeks : I have added GRCh38.p13 PATCHES to the `.alt` file and ended entries with NM tag, which was sufficient for `postalt.js`.

**Comment by wangshun1121** [comment]
Mark！

**Comment by YuGe** [comment]
Mark!
