### ISSUE TITLE
0.7.17 precompiled binary for Linux

### ISSUE THREAD

**Issue by zeus19900814** [lh3/bwa#233]
Hi,

I am wondering if you could provide the latest precompiled bwa binary for Linux. It looks like the bwakit link only contains source code.

Thank you,
John

**Comment by DarioS** [comment]
Version 0.7.17 has been released for a long time (I wonder if there will ever be a version 1.0.0). So long ago that many Linux distributions already have it ready for you. For example, the current version of Debian [has it](https://packages.debian.org/sid/bwa) and Debian is quite slow to package software. So, you can simply do `sudo apt-get install bwa` if you have recent Debian or Ubuntu varieties of Linux and a similar command for other varieties.

**Comment by lh3** [comment]
It should be easy to compile bwa. Let me know if you have problems with installation.
