### ISSUE TITLE
Add UR field to SQ line in SAM output

### ISSUE THREAD

**Issue by marchoeppner** [lh3/bwa#236]
Hi,

so this is probably an odd edge case (or I am missing something), but I have a WGS pipeline that uses BWA , followed by a bunch of BAM file processing stages (GATK pipeline, basically). 
Since the data are so huge, I would like for the final read alignment to be stored in CRAM format. So far so good, this is possible with GATK/Samtools no problem. 

However, reading CRAM files apparently requires information on the genome FASTA file to be included with the CRAM file (or be provided from the command line, as done by Samtools and GATK using the -T and -R flags respectively). 

However, apparently the convention is to actually encode that information in the SQ header for each sequence entry using the UR tag (URI) https://samtools.github.io/hts-specs/SAMv1.pdf

Unfortunately, there seems to be no good way to edit these SQ entries after the fact (short of modifying the header and re-inserting it through scripting, which is clunky...); and since these lines are created by BWA, I was wondering if it would perhaps make sense to make this an option?

Cheers,
Marc

**Comment by jmarshall** [comment]
If you're using `bwa mem`, you want the `-H` option.

See also https://github.com/lh3/bwa/issues/147#issuecomment-376120864. I'm increasingly tempted to write PRs for bwa and minimap2 to implement _\<idxbase\>.hdr_ as suggested in that comment.

**Comment by marchoeppner** [comment]
Yep, that'll do it. Thanks.
