### ISSUE TITLE
Is it possible to specify the temporary / scratch directory for BWA mem?

### ISSUE THREAD

**Issue by illusional** [lh3/bwa#238]
I'm attempting to run `bwa mem` on Google Cloud Platform, and generally the process is to keep the boot disk size small, and mount a larger partition. Unfortunately `bwa mem` was writing files to the boot disk which caused the disk to become full, and the execution to stop.

My short term fix was to up the boot disk size until it worked, but I was hoping to find a way to tell `bwa` to use a different directory for temp files. A command line param is easiest, but I'd also be stoked if there's environment variable that does it.

This was the result of `sudo df -h` just before the execution finished running:

```
Filesystem      Size  Used Avail Use% Mounted on
udev             10M     0   10M   0% /dev
tmpfs            12G  8.3M   12G   1% /run
/dev/sda1        99G   17G   79G  17% /
tmpfs            30G     0   30G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            30G     0   30G   0% /sys/fs/cgroup
/dev/sdb         30G   15G   14G  51% /mnt/local-disk
```

**Comment by lh3** [comment]
Bwa mem doesn't generate temporary files.
