### ISSUE TITLE
I want to know how to control the matching rate.

### ISSUE THREAD

**Issue by mireiya** [lh3/bwa#246]
Hi, everyone. I'm student of graduated school.
I'm trying to map PACBIO reads to reference genome  in ”bwa mem" command.

I want to change the matching rate of mapping   (pacbio reads - reference genome)  myself.

So, I want to know the two points.

How to control
1.  the match rate of seeds
2.  the total matching rate (of read / reference genome)

How can I change the value ?

kind regards.

**Comment by lh3** [comment]
Use minimap2.
