### ISSUE TITLE
run-gen-ref generates alt file for hs38a but not for hs37d5

### ISSUE THREAD

**Issue by jessrosenfield** [lh3/bwa#248]
Is there a reason that `hs37d5ss.sam.gz` or `hs37d5ss.info` (located under ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/phase2_reference_assembly_sequence/) should not be used for the generation of an alt file for alt-aware alignments for decoy contigs that have alignments to the primary reference?

**Comment by lh3** [comment]
Those are not ALT-to-ref alignment and should not be used.

**Comment by jessrosenfield** [comment]
Would it not be beneficial to use the ref IDs as described in [Step 1: BWA-MEM mapping](https://github.com/lh3/bwa/blob/master/README-alt.md#step-1-bwa-mem-mapping) even though their alignments to the primary reference should not be used in the postprocessing (step 2)?

**Comment by jessrosenfield** [comment]
Although I suppose with the current format of hs37d5.fa.gz it is not possible to directly use this information and a concatenation of human_g1k_v37.fasta and hs37d5ss.fa.gz might need to be used instead?

**Comment by jessrosenfield** [comment]
Or perhaps even just the ref ID of the concatenated decoys (hs37d5) could be ignored for generating mapQ.

**Comment by lh3** [comment]
The majority of decoy sequences are not alternate haplotypes. They are distinct from ALT contigs.
