### ISSUE TITLE
BWA-MEM doesn't return all matches (very short sequences)

### ISSUE THREAD

**Issue by Permafacture** [lh3/bwa#256]
Perhaps this is an abuse of bwa, but for genomic specificity checking for primers I am aligning just the last 10 bp of the 3` end since from NGS data we see that even that is extensible.  I am getting a number of exact matches, but not all of them.  I know because I'm not getting the exact match that causes an off target product we are seeing.  And I'm not getting any of less than an exact match, though my scoring should allow it.

Specifically: 'CAACAAAACAG' should map exactly to 7:116423437-116423449 using HG19

For what it's worth, I'm using bwapy and am doing further processing in python.

**Comment by ekg** [comment]
Why not directly use a compressed suffix array library? If you are just
looking for exact matches then you don't need much more than that.

**Comment by Permafacture** [comment]
Because I do want to allow mismatches, it's just that the exact match is the clearest case of a result not coming through.

**Comment by ekg** [comment]
Try `-k 8 -T 0`.

>

**Comment by yanlinlin82** [comment]
and also `-a`.

**Comment by Permafacture** [comment]
I had tried something like this already but tried these three parameters exactly and still only get about 10 results when there are thousands in HG19.  For what it's worth, bowtie2 doesn't like doing this either, so I probably just need to come up with my own solution using a compressed suffix array.  It would be nice to seamlessly blend short sequences with no mismatches with sequences of increasing length and amount of mismatch.  So, keep this open if y'all think bwa-mem should be able to do this, otherwise you can close it

**Comment by Permafacture** [comment]
Well, If I pass in a longer sequence with the same parameters, bwa respects the seed parameter better than bowtie2 so I guess this is the best I can get which works alright
