### ISSUE TITLE
bwa mem uses more threads than requested

### ISSUE THREAD

**Issue by wbsimey** [lh3/bwa#260]
I am using bwa mem version  0.7.17-r1188 on a 72 thread (4 CPU) ubuntu server with 380 GB RAM.
my script includes 

`'bwa mem -t 64 $Ref $R1 $R2 > ${basename}'`

but it is using way more than 64 threads, as you can see on the attached image.

How do I control the total number of threads bwa will use?

![image](https://user-images.githubusercontent.com/2200085/70004073-ee06a500-1519-11ea-8825-54b3f35ef632.png)

**Comment by lh3** [comment]
Please use top. From htop, you can't tell how many CPUs bwa is using.

**Comment by lh3** [comment]
Actually, htop is saying 6477%.

**Comment by wbsimey** [comment]
Sorry, I must be reading htop wrong. I see the 6477% for the top row, but there are many other bwa rows each with ~100%. But, you are correct, top shows total threads per process.
