### ISSUE TITLE
Some questions about multithreads in bwa?

### ISSUE THREAD

**Issue by Zea1nfO** [lh3/bwa#262]
When i running the bwa via command ：
**bwa mem -a -t 30 ref.fa sample.fa > res.sam**
But the bwa only use one thread, whats wrong with it?
Besides the bwa i used is bwa-0.7.10.

And i got the question:
The bwa-0.7.10 has the e option that discard full-length exact matches, but the latest bwa does not have the option.
So how can fullfil the "discard full-length exact matches" in the lastest bwa?
Or should i use some other tools carry out it.

**Comment by Zea1nfO** [comment]
Besides, it seems that bwa got stuck after show this message:
**[M::main_mem] read 40150 sequences (300002988 bp)...**

**Comment by lh3** [comment]
Don't use bwa-mem for long sequences.
