### ISSUE TITLE
 BWA MEM ! Why Different threads cause Slightly different  bam file?

### ISSUE THREAD

**Issue by baimianer** [lh3/bwa#272]
![image](https://user-images.githubusercontent.com/21122009/75426208-21bd6380-597f-11ea-9aa5-457a139e8ef6.png)

![image](https://user-images.githubusercontent.com/21122009/75426227-2da92580-597f-11ea-84f2-c5c7a87a1e76.png)

I want to know why different thread settings cause BAM
Slightly different

**Comment by rbh** [comment]
You'll probably want to specify your insert size. Otherwise each thread will make its own estimate based on the chunk of reads it processes.

Best,

Rasmus

**Comment by lh3** [comment]
Please use a fixed `-K`.
