### ISSUE TITLE
bwa mem "killed" in docker container

### ISSUE THREAD

**Issue by pwanj** [lh3/bwa#276]
Hi,

I am trying to run bwa mem command inside a docker container. Inside the container, I installed it using apt-get install bwa in ubuntu:16.04

For some reason, the bwa mem command exits without any error. just a message "killed". I tried running the same files, same bwa version in hpc and it is working fine. I am not able to figure out what could be causing this error.

Please can you tell me if you have any thoughts about this. What could be causing it to exit with the message "Killed". I would really appreciate your help.

Thanks!

**Comment by yfarjoun** [comment]
Usually this means that the program used much more memory than you provided
to the machine.

**Comment by pwanj** [comment]
I see. Thanks! It worked when I increased the memory. Thank you for your help. I appreciate it.

**Comment by rhlyadav21** [comment]
how can I increase my memory?
