### ISSUE TITLE
bwa index compatibility

### ISSUE THREAD

**Issue by EricDeveaud** [lh3/bwa#281]
Hello, 

on our cluster we are providing a wide range of bwa versions to our users
range from 0.5.9 to 0.7.17 
as we also provide some centralised bwa indexes, we would like to know which 
I would like to know if you can provide an index format compatibility chart based on version

from what I quickly and dirty tested 
0.5.9 indexes are not compatible with 0.6.* and 0.7.* versions
0.6.* and 0.7.* indexes are inter operable 

regards

Eric

**Comment by lh3** [comment]
> 0.5.9 indexes are not compatible with 0.6.* and 0.7.* versions
> 0.6.* and 0.7.* indexes are inter operable

That's correct.
