### ISSUE TITLE
How BWA determine a paired-end read is proper or improperly paired?

### ISSUE THREAD

**Issue by NTNguyen13** [lh3/bwa#299]
Hi, I recently stumble upon some issue related to improperly paired reads. From my understanding, they are marked with SAM Flag 0x2, and they need to suffice those criteria:
- 2 paired reads need to be on the same chromosome.
- 2 paired reads don't map 'too far' from each other.

I can understand the first criteria, but hơ's about the second one? When are 2 reads 'close enough' to be considered as 'properly' paired?

Thank you very much

**Comment by slw287r** [comment]
For certain sample type such as cfDNA the proper insert size is not that ‘proper’. The nucleosomes’ foot prints influence fragment sizes: 165bp major peak and ~300 minor peak.
