### ISSUE TITLE
Is the license to bwa MIT or GPLv3?

### ISSUE THREAD

**Issue by nh13** [lh3/bwa#304]
Each source file has an MIT license but the [COPYING](https://github.com/lh3/bwa/blob/master/COPYING) document says GPL v3.

**Comment by nh13** [comment]
I found this: http://bio-bwa.sourceforge.net/bwa.shtml#13, but [`fastmap.c`](https://github.com/lh3/bwa/blob/master/fastmap.c) for example is MIT, but not one of "Sorting, hash table, BWT and IS libraries are distributed under the MIT license."

**Comment by lh3** [comment]
bwt_gen.c is GPL'd.
