### ISSUE TITLE
Allow specifying of in_3.fastq

### ISSUE THREAD

**Issue by ghuls** [lh3/bwa#317]
It would be great if a in_3.fastq could be specified. A third FASTQ file is often used for single-cell ATAC data to indicate the cell barcode. This third read, is not meant to be be mapped, but the sequence and quality should be added as a separated BAM tag.

For example in sinto, they use bwa for mapping, but to add the barcode to the BAM file, they add the R3 read sequence in front of each readname in both FASTQ files. This kind of FASTQ manipulation should not be needed to add the barcode in the BAM file andd should be easy to add directly to the mapper:
https://timoast.github.io/sinto/scatac.html

**Comment by lh3** [comment]
Please use -C to copy over fastq comments.
