### ISSUE TITLE
Wrong SAM file header generated with BWA -mem option

### ISSUE THREAD

**Issue by stachyris** [lh3/bwa#323]
Hi, 
I am trying to map paired end reads to an indexed reference genome downloaded from Ensemble using bwa -mem option and generated SAM file has non standard header intermittently. Instead of @SQ, it has @S@SQ header in few lines in overall file. 

Please note that I am using 0.7.17-r1188 bwa version and  0.1.19-44428cd Samtools version on a centos7 cluster. Is this SAMTOOLS or BWA issues.? Previously, I have successfully mapped without any issue with same indexed genome but different set of RAW files. 

Any help to solve the issue is highly appreciated. 
Thank you, 
Vinay

**Comment by mp15** [comment]
On behalf of the samtools team, please upgrade! Samtools 0.1.19 is more than 8 years old, we are currently on 1.14 which has 8 years of bugfixes we found along the way.

Also it is helpful if you supply the entire alignment command line you used to create this aberrant file, as well as the species you are aligning and how you indexed the reference.

**Comment by stachyris** [comment]
Hi @mp15 Thank you for the quick reply. 
It appears that local SAMTool is the newer version but the one in root is older version, shall upgrade that as well.  

So I am using Athene cunicularia as the the reference genome and it was indexed using **bwa index ref.fa** command to map the reads from other Athene species (We had no issues previously when we did the same process for data from different individual). 

In order to map the genome I am following the basic command: mpirun -np 40 bwa mem -t 40 -p -M /path/to/ref/Athene_cunicularia.athCun1.dna.toplevel.fa  raw_adaptersmarked_unmapped.fastq > fo_adaptersmarked_aligned.sam

Thank you, 
Vinay

**Comment by stachyris** [comment]
Hi @mp15 This issue has been resolved. 
We figured out that it was the cluster problem. When job was submitted using mpirun for parallel processing, for some reason it was looping and it was writing the same content for n number of times where n is the number of cores asked for the job. 

Appreciate it. Thank you.
