### ISSUE TITLE
PACBIO contigs with BWA-MEM

### ISSUE THREAD

**Issue by khush876** [lh3/bwa#329]
Hi, 

I have assembled a plant genome using PACBIO and would like to add ILLUMINA data for finishing up. However, I am not sure how to proceed with it.

bwa mem pacbio.ref.fa reads1.fastq reads2.fastq > aln.sam

or 

bwa mem -x pacbio.ref.fa reads1.fastq reads2.fastq > aln.sam

Any suggestion?

**Comment by lh3** [comment]
```sh
bwa index ref.fa
bwa mem -t16 ref.fa read1.fq read2.fq
```

**Comment by khush876** [comment]
thanks
