### ISSUE TITLE
bwa mem - fastq sequence order

### ISSUE THREAD

**Issue by Fazulur** [lh3/bwa#338]
Dear bwa team,

I observed few differences in number of variant calls when i compared calls generated from original fastq & converted fastq from bwa generated bam.

I have used the below link to convert back bwa aligned bam to fastq file. 
https://gist.github.com/darencard/72ddd9e6c08aaff5ff64ca512a04a6dd

I ran alignment again using bwa mem and then variant calling using GATK4. When I compared variant calls generated from bam (from original fastq) & bam (from converted fastq), I observed few difference in number of variants. I found this difference is due to order of sequence identifiers in fastq files. Then i sorted sequence ids in converted fastq in same order of original fastq using BBMap filterbyname.sh function and observed 100% overlap in variant calls from original fastq vs converted fastq.

Could you please let me know whether this difference is expected when sequence identifiers in fastq are in different order? 

Thanks In Advance
Fazulur Rehaman

**Comment by lh3** [comment]
Yes, expected. Also, that gist is suboptimal. You should use `samtools collate` instead.

**Comment by Fazulur** [comment]
Dear Heng Li,

Thanks a lot for your prompt response & suggestion. 
Can I ignore the difference calls I got due to the order of sequences in fastq?

First I tried samtools collate to get back bamtofastq. Since I am not getting exact fastq files back from bam, i used the above gist approach.

Here is the command i used with samtools collate
**samtools collate -@ 32 -uO  test.bwa.bam tmp- | samtools fastq -@ 32 -s test.single.fastq -0 test.unpaired.fastq -1 test_R1_ver1.fastq.gz -2  test_R2_ver1.fastq.gz -**

Could you please suggest us how I can get exact fastq files from samtools collate.

Thanks In Advance
Fazulur Rehaman
