### ISSUE TITLE
improper read pair status given; for pairs falling outside insert size boundaries for low complexity amplicon library

### ISSUE THREAD

**Issue by alexander-e-f-smith** [lh3/bwa#350]
Hi 
I have a low complexity library for 4 amplicons which can lead to improper pair status being allocated by BWA MEM to specific amplicons according to the relative amplicon concentration in the sample library mix.  This is seemingly a consequence of the calculations bwa makes for low and high boundaries for insert size (when falling outside these, read pair given improper read status; 145 and 97 flags in this case).  Apart from either correcting at the lab level or some sort of number balancing of fastq reads prior to alignment, is there another way to adjust this calculation in BWA itself, or best practises for fixing this after alignment safely.

**Comment by lh3** [comment]
Option `-I`
