### ISSUE TITLE
how to attach XM tag

### ISSUE THREAD

**Issue by S-111** [lh3/bwa#352]
I would like to use XM tag after mapping, but the output sam file did not has XM tag.
how to attach XM tag?
I executed the command below.
Thank you for your cooperation!

`bwa mem -x pacbio ref.fasta input.fastq > out.sam`
Version: 0.7.17-r1198-dirty

**Comment by lh3** [comment]
You can compute from NM and CIGAR. Also, for pacbio data, use minimap2.
