### ISSUE TITLE
bwa mem fails to identify paired-end sequences with 'not enough pairs' message

### ISSUE THREAD

**Issue by cokelaer** [lh3/bwa#357]
I faced an issue with paired data not being recognised as paired with the **bwa mem** command.

The data was mapped (on mm10 genome; mouse) using bowtie2 with no problem indicating that the reads are correctly and properly paired and labelled. Using bwa, a bamtools stats gives this log file: 

    Total reads:       951928338
    Mapped reads:      1743131	(0.183116%)
    Forward strand:    949661678	(99.7619%)
    Reverse strand:    2266660	(0.238112%)
    Failed QC:         0	(0%)
    Duplicates:        0	(0%)
    Paired-end reads:  951928338	(100%)
    'Proper-pairs':    0	(0%)
    Both pairs mapped: 47163	(0.00495447%)
    Read 1:            475960913
    Read 2:            475967425
    Singletons:        1695968	(0.178161%)

Here, we can see a low mapping, the R1 and R2 paired-end (100%) but 0 proper-pairs. 

Then, we mapped the data (here on a sub sample of 2 paired reads; 500 reads or 95Mreads gives the same kind of results):

    [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
    [M::mem_pestat] skip orientation FF as there are not enough pairs
    [M::mem_pestat] skip orientation FR as there are not enough pairs
    [M::mem_pestat] skip orientation RF as there are not enough pairs
    [M::mem_pestat] skip orientation RR as there are not enough pairs
    [M::mem_process_seqs] Processed 4 reads in 0.001 CPU sec, 0.004 real sec
    ....
    V350063195L4C001R00100000265	77	*	0	0	*	*	0	0			AS:i:0	XS:i:0
    V350063195L4C001R00100000265	141	*	0	0	*	*	0	0			AS:i:0	XS:i:0
    R00100000266	77	*	0	0	*	*	0	0			AS:i:0	XS:i:0
    R00100000266	141	*	0	0	*	*	0	0		        AS:i:0	XS:i:0
    [main] Version: 0.7.17-r1188
    [main] CMD: /opt/gensoft/exe/bwa/0.7.17/bin/bwa mem ../reference/genome.fasta temp_1.fq temp_2.fq
    [main] Real time: 0.822 sec; CPU: 0.810 sec

We can see here that the FF/FR/RF/RR are all set to zero. We can also see that the SAM results do not find any mate. 

The version of bwa used is 0.7.17.

The data is MGI data, not Illumina, but the bowtie2 successful alignment indicates that this is not the issue.

I have seen some indication about insert size not recognised in some forums due to large insert, however from the bowtie results looks like reasonable insert size . 
![temp](https://user-images.githubusercontent.com/778821/175259926-82f4d7c5-781b-44df-9087-0c1d89e6da09.png)

Any help would be appreciated. thanks in advance.

I'm not providing any files for testing since the genome used is quite huge (several Gb)

**Comment by RominaSSBatista** [comment]
Hi @cokelaer Thomas, did you manage to sort this issue? I am having exactly the same. The FF/FR/RF/RR are all set to zero, as well. Any thoughts? I would appreciate if you could share it here. Thank you, Romina.

**Comment by Isoris** [comment]
same here any updates ? it worked just previrouly on a single contig but when I put the whole genome it doesnt work ?

[M::process] read 2 sequences (268 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 1, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 2 reads in 0.044 CPU sec, 0.041 real sec
[M::process] read 2 sequences (268 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 1, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs

**Comment by lh3** [comment]
These are caused by wrong input or wrong command line options.

**Comment by Isoris** [comment]
Do you think that It could be caused by using a variable name $assembly
instead of the hardcoded name?

**Comment by Isoris** [comment]
Ok thank you so much for your answer. It works now.

**Comment by Isoris** [comment]
Hello, 
do you think it could be caused by the lack of MPI support because I got the same error and I have use -N 2 in the slurm header?
