### ISSUE TITLE
Trailing whitespace in SAM file

### ISSUE THREAD

**Issue by dylanlawrencebio** [lh3/bwa#371]
Running into an interesting issue with SAM file generation. There seems to be a trailing empty line in my SAM file after run completion, this causes a failure when I attempt to convert the SAM to a BAM.

BWA command:
`conda run -n id_mapping bwa mem -t 1 /path/to/reference_fasta.ext /path/to/r1.ext /path/to/r2.ext > alignment.sam`

Samtools command:

`conda run -n id_mapping samtools view -bo alignment.bam alignment.sam`

Error:

    2022-08-26T13:47:18.117645197Z [W::sam_read1_sam] Parse error at line 11340517

    2022-08-26T13:47:18.117668726Z samtools view: error reading file "/sbgenomics/workspaces/168f5b1c-74bb-44ed-8818-75354da02e2e/tasks/ef0545d6-bdac-4953-98d7-6f797e719345/bwa_index_and_mem/alignment.sam"

I have checked and that line number is the final line of the file which is blank.

**Comment by jmarshall** [comment]
This is probably an artefact of `conda run`.

Use `bwa mem -o alignment.sam …` rather than redirecting _the output of `conda run`_.

**Comment by dylanlawrencebio** [comment]
That did appear to be the problem!
