### ISSUE TITLE
bwa mem ont2d

### ISSUE THREAD

**Issue by Oksanak22** [lh3/bwa#375]
Hello people!

I try to run the command "bwa mem -x ont2d ref.fa reads.fq > aln.sam" for  Oxford Nanopore reads, as it shows at https://github.com/lh3/bwa. But I don't get what the mathematical apporach is used for this kind of alignment. 

Thank you.

**Comment by lh3** [comment]
Please use minimap2.

**Comment by Oksanak22** [comment]
Thank you, lh3 for your advice, I will do it. 
But just for curiosity, I would like to know the mathematical approach for 'bwa mem"
