### ISSUE TITLE
Error coming during compilation

### ISSUE THREAD

**Issue by achintkansal** [lh3/bwa#387]
This is the type of error I am getting? What to do?
`
gcc -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS bwashm.o bwase.o bwaseqio.o bwtgap.o bwtaln.o bamlite.o bwape.o kopen.o pemerge.o maxk.o bwtsw2_core.o bwtsw2_main.o bwtsw2_aux.o bwt_lite.o bwtsw2_chain.o fastmap.o bwtsw2_pair.o main.o -o bwa -L. -lbwa -lm -lz -lpthread -lrt
/usr/bin/ld: ./libbwa.a(rope.o):/home/achint/Desktop/BWA/bwa-0.7.17/rle.h:33: multiple definition of `rle_auxtab'; ./libbwa.a(bwtindex.o):/home/achint/Desktop/BWA/bwa-0.7.17/rle.h:33: first defined here
/usr/bin/ld: ./libbwa.a(rle.o):/home/achint/Desktop/BWA/bwa-0.7.17/rle.h:33: multiple definition of `rle_auxtab'; ./libbwa.a(bwtindex.o):/home/achint/Desktop/BWA/bwa-0.7.17/rle.h:33: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:30: bwa] Error 1`

**Comment by guyleonard** [comment]
This error was fixed here:
https://github.com/lh3/bwa/commit/2a1ae7b6f34a96ea25be007ac9d91e57e9d32284

I think this will still show up though if you download the release https://github.com/lh3/bwa/releases/tag/v0.7.17 rather than cloning the repository.
