### ISSUE TITLE
Question about XA Tag and MAPQ Values

### ISSUE THREAD

**Issue by zqlns** [lh3/bwa#404]
After using BWA-MEM for alignment, I've noticed that SAM files contain XA tags with information about alternative hits for some reads. What's intriguing is that the MAPQ values associated with these alternative hits are greater than 0, which seems to contradict the common belief that reads with multiple hits should have a MAPQ of 0.

I am curious about the reasons behind this phenomenon. Should reads with XA tags and MAPQ values greater than 0 be considered for downstream analysis, or should they be filtered out? 

Thanks!

**Comment by lh3** [comment]
XA doesn't consider read pairs. MAPQ does.
