### ISSUE TITLE
How can i obtain all the regions reads hit. (in duplication region)

### ISSUE THREAD

**Issue by liukeweiaway** [lh3/bwa#427]
If a reads hit multiple regions, can i use bwa obtain these regions in sam/bam file?

**Comment by nicolo-tellini** [comment]
the option ` -a:  output all found alignments for single-end or unpaired paired-end reads. These alignments will be flagged as secondary alignments.`  The XA tag gives additional info about multiple locations. see https://github.com/lh3/bwa/blob/79b230de48c74156f9d3c26795a360fc5a2d5d3b/README-alt.md?plain=1#L76

**Comment by liukeweiaway** [comment]
> the option `-a: output all found alignments for single-end or unpaired paired-end reads. These alignments will be flagged as secondary alignments.` The XA tag gives additional info about multiple locations. see
> 
> https://github.com/lh3/bwa/blob/79b230de48c74156f9d3c26795a360fc5a2d5d3b/README-alt.md?plain=1#L76
The answer help he a lot! Thanks
