### ISSUE TITLE
feature proposal: allow tag name to be specified for storing fastq comment for read

### ISSUE THREAD

**Issue by bpow** [lh3/bwa#429]
I understand this is really a matter of convenience / "command-line syntactic sugar", but hear me out...

As currently implemented, the `-C` option allows the comment field from a fastq file to be stored along with a read, but it requires that the comment be in the SAM tag format (e.g., `BC:Z:ATAACTA`).

fastq files frequently come with comments that aren't in that format. For instance, CASAVA demultiplexing may provide a fastq comment field that looks like `1:Y:18:ATCACG`. While it's not "too hard" to write something that could be piped through to prepend the comment with something to satisfy that constraint, it would be convenient to be able to assign the tag name and/or type by the bwa command line.

Proposal:
* add option `-g` for 'fastq comment tag name', with a single string argument (that would be 2 characters)
* when `-g` is provided, this implies `-C`, and essentially prepends the fastq comment with the relevant info to make it conform to the SAM tag specification.

For instance, a fastq file with a sequence header line like:

```
@seqid 1:Y:18:ATCACG
```

When run using `bwa mem -g XC ...` would result in the tag `XC:Z:1:Y:18:ATCACG` being associated with the read in the resulting output.

As a variation, the string parameter of `-g` could require or allow the tag type to be specified (e.g., `-g XC:Z`).

**Comment by lh3** [comment]
> While it's not "too hard" to write something that could be piped through to prepend the comment with something to satisfy that constraint, it would be convenient to be able to assign the tag name and/or type by the bwa command line.

Moving too many functionalities into the core increases the maintenance burden. How many is too many is debatable but I think this feature is easy enough to be implemented independent of bwa.
