### ISSUE TITLE
bwa index of 300GB multifasta fails at bwt2sa stage without error

### ISSUE THREAD

**Issue by hazmup** [lh3/bwa#436]
I have downloaded several thousand genomes from RefSeq into a multifasta file and I want to index it. The file is ~300GB. When I run `nohup bwa index -b 100000000 combined_sequences.fna &> bwa_indexing.log &` it fails at `[bwa_index] Construct SA from BWT and Occ...`. I switched from a 512GB RAM machine to a 1TB RAM machine and tried to resume with `nohup bwa bwt2sa combined_sequences.fna.bwt combined_sequences.fna.sa &`, however it failed again without any message at all. What could be wrong?

**Comment by lh3** [comment]
Probably a memory issue. Try smaller batches.

**Comment by hazmup** [comment]
Do you mean that the `bwt` file is corrput and the first steps need to be repeated? Because I cannot find a batch parameter for `bwa bwt2sa`, and the construction of the `bwt` file did not fail. Thank you.

**Comment by hazmup** [comment]
It seems that `bwa bwt2sa` had not actually crashed, even though I am pretty sure it was not listed in the running processes. Probably an oversight on my part. In any case I am marking this as resolved, thank you @lh3 !
