### ISSUE TITLE
Can I bulid a new reference for bwa  ? 

### ISSUE THREAD

**Issue by WinterLi1993** [lh3/bwa#56]
Dear Professor,
         I wanna use a specified gene sequence to build a reference , and  then mapp PE fastq files (fq1,fq2) to this new reference gene genome  via BWA .  
       that's just a thought ,I do not konw it's availble ?
       if availble,  which algorthims should I choose from BWA ??

BEST

**Comment by lh3** [comment]
Just run bwa normally.

**Comment by WinterLi1993** [comment]
Dear Professor,
      if a read happened at gene fusion,   multi alignment will be appeared at a bam file ? I do not konw BWA whether will represent such these records .
