### ISSUE TITLE
run-gen-ref hs38 results in unexpected EOF "No such directory "genbank/genomes/Eukary…"

### ISSUE THREAD

**Issue by srmcgee** [lh3/bwa#66]
I'm trying to install GRCh38 and it fails each time with an unexpected end of file (run-gen-ref for hs38a and hs38DH fail exactly the same way).  It seems to be unable to locate all of the chromosomes, unplaced and unlocalized contigs and EBV files.

Any help would be greatly appreciated.

Thank you very much.

-bash-4.1$ bwa.kit/run-gen-ref hs38
--2016-05-27 15:52:54--  ftp://ftp.ncbi.nlm.nih.gov/genbank/genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_full_analysis_set.fna.gz
           => “-”
Resolving ftp.ncbi.nlm.nih.gov... 130.14.250.10, 2607:f220:41e:250::12
Connecting to ftp.ncbi.nlm.nih.gov|130.14.250.10|:21… connected.

Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD … done.
==> TYPE I ... done.  ==> CWD (1) /genbank/genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines … 
No such directory “genbank/genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines”.

gzip: stdin: unexpected end of file

**Comment by snashraf** [comment]
I am getting same error as well.  I am trying to download as mentioned here in this https://github.com/lh3/bwa/tree/master/bwakit

**Comment by wdecoster** [comment]
The hard-coded path in run-gen-ref to genbank ftp is no longer valid, resulting in this problem.

**Comment by snashraf** [comment]
Yes, I was able to get correct link.

Thanks
Najeeb

**Comment by lh3** [comment]
Via #123.
