### ISSUE TITLE
BWA won't work when the first letter of the quality line in FASTQ file is '@' symbol.

### ISSUE THREAD

**Issue by johnbach168** [lh3/bwa#74]
If the first letter of the forth line in every reads, indicating the quality, is '@' symbol, will make BWA process terminated. For instance:

> @sequences_name
> ATTGCATGCATGC
> +
> @@DDDAD,AAFDF

To solve this problem, I have to replace the initio '@' in the quality line to 'A', hoping the replacement won't affect the coming analysis.
Also, if two reads are paired, and their names are almost identical but end with "-1" and "-2", which can distinguish them, BWA will abort too. I think you can identify two paired reads' names without considering the last number if it is "1" or "2".

**Comment by lh3** [comment]
I don't think bwa has any issues with leading `@` in quality. For example, the following sequence is mapped just fine:
```
@1
CACTAAGCACACAGAGAATAATGTCTAGAATCTGAGTGCCATGTTATCAAATTGTACTGA
+
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```
Show me the exact command line and the sequence you have problem with.

The convention is to have `/1` and `/2` at the end. Please follow the convention.

**Comment by johnbach168** [comment]
Thanks for your reply.
Here is my command:
bwa mem -t 12 -M AaegL4.masked.masked.top3.fasta trimmed_dilutions_3_barcoded_1.fastq trimmed_dilutions_3_barcoded_2.fastq >trimmed_dilutions_3_vs_Aaegypti_masked_masked_top3-BWA.sam
The error was:
[mem_sam_pe] paired reads have different names: "SL-HDG:781:H32CHADXY:2:2214:6469:48527:BX:AACACGTAGCGAAC:BC:TCGCCAGC", "@@DDDDD,AAFDFCB22CBAB?HH<AFGHG6CGIIIGEHHIGG?B9/9?@)8/BB<FEGDA7=)..?=A;;BA,6;(-5;3-;@(,5;A<(5544(:43((4083(&(++9:A@4(4)+((+(:@(4(5&&)05((+(++4:((+(+)("
So I use grep to find that read both in two paired files:
$ grep -n -A 3 'SL-HDG:781:H32CHADXY:2:2214:6469:48527:BX:AACACGTAGCGAAC:BC:TCGCCAGC' trimmed_dilutions_3_barcoded_1.fastq115889:@SL-HDG:781:H32CHADXY:2:2214:6469:48527:BX:AACACGTAGCGAAC:BC:TCGCCAGC115890-ACGGACCATCAGACAACGAACCATCAGAGGACGGACCATCAGACAACGAACCATCAGAGGACAGACGATCAGACAACGAACCATCAGAGGACGGACCATCAGACAACGAACCATCAGAGGACGGACC115891-+115892-CGDGHFGGGGHIIIGCHA5CGEHHEEE<@=>=?;>62<C>CC:3<?BB(200<@>(4(:08<(2>A&&28&4>:(<<588&084(((((+(2&&)&&24(43:(2<B3+2&&+49:+(:((+&&)))
$ grep -n -A 3 'SL-HDG:781:H32CHADXY:2:2214:6469:48527:BX:AACACGTAGCGAAC:BC:TCGCCAGC' trimmed_dilutions_3_barcoded_2.fastq
115889:@SL-HDG:781:H32CHADXY:2:2214:6469:48527:BX:AACACGTAGCGAAC:BC:TCGCCAGC115890-CCTCTGATTGTTCGTTTTCTGATGGTCCGTCCTCTGATGGTTCGTTGTCTGATGGTCCGTCCTCTGATGGTTCGTTGTCTGATGGTCCGTCTTCTGATGGTTCGTTGCCTGATGGTTCGTCCTCTGGTCGGTCGTCCTCTGATGGTTCGT115891-+115892-@@@DDDDD,AAFDFCB22CBAB?HH<AFGHG6CGIIIGEHHIGG?B9/9?@)8/BB<FEGDA7=)..?=A;;BA,6;(-5;3-;@(,5;A<(5544(:43((4083(&(++9:A@4(4)+((+(:@(4(5&&)05((+(++4:((+(+)(

I have no idea why error occured. Please help. Thank you very much.


Best,

Yang


Date: Sat, 18 Jun 2016 15:44:56 -0700

**Comment by lh3** [comment]
Sorry, I can't read your message as everything is concatenated together. Please use markdown to format.

**Comment by johnbach168** [comment]
I am sorry about that. Thanks for your reply.
Here is my command:
>  bwa mem -t 12 -M AaegL4.masked.masked.top3.fasta  trimmed_dilutions_3_barcoded_1.fastq  trimmed_dilutions_3_barcoded_2.fastq  >trimmed_dilutions_3_vs_Aaegypti_masked_masked_top3-BWA.sam
The error was:
>  [mem_sam_pe] paired reads have different names:  “SL-HDG:781:H32CHADXY:2:2214:6469:48527:BX:AACACGTAGCGAAC:BC:TCGCCAGC”,  “@@DDDDD,AAFDFCB22CBAB?HH<AFGHG6CGIIIGEHHIGG?B9/9?@)8/BB<FEGDA7=)..?=A;;BA,6;(-5;3-;@(,5;A<(5544(:43((4083(&(++9:A@4(4)+((+(:@(4(5&&)05((+(++4:((+(+)(“
So I use grep to find that read both in two paired files:
>  $ grep -n -A 3  ‘SL-HDG:781:H32CHADXY:2:2214:6469:48527:BX:AACACGTAGCGAAC:BC:TCGCCAGC’  trimmed_dilutions_3_barcoded_1.fastq
> 115889:@SL-HDG:781:H32CHADXY:2:2214:6469:48527:BX:AACACGTAGCGAAC:BC:TCGCCAGC
>   115890-ACGGACCATCAGACAACGAACCATCAGAGGACGGACCATCAGACAACGAACCATCAGAGGACAGACGATCAGACAACGAACCATCAGAGGACGGACCATCAGACAACGAACCATCAGAGGACGGACC
> 115891-+
>   115892-CGDGHFGGGGHIIIGCHA5CGEHHEEE<@=>=?;>62CC:3<?BB(200<@>(4(:08<(2>A&&28&4>:(<<588&084(((((+(2&&)&&24(43:(2<B3+2&&+49:+(:((+&&)))
>  $ grep -n -A 3  ‘SL-HDG:781:H32CHADXY:2:2214:6469:48527:BX:AACACGTAGCGAAC:BC:TCGCCAGC’  trimmed_dilutions_3_barcoded_2.fastq
> 115889:@SL-HDG:781:H32CHADXY:2:2214:6469:48527:BX:AACACGTAGCGAAC:BC:TCGCCAGC
>   115890-CCTCTGATTGTTCGTTTTCTGATGGTCCGTCCTCTGATGGTTCGTTGTCTGATGGTCCGTCCTCTGATGGTTCGTTGTCTGATGGTCCGTCTTCTGATGGTTCGTTGCCTGATGGTTCGTCCTCTGGTCGGTCGTCCTCTGATGGTTCGT
> 115891-+
>   115892-@@@DDDDD,AAFDFCB22CBAB?HH<AFGHG6CGIIIGEHHIGG?B9/9?@)8/BB<FEGDA7=)..?=A;;BA,6;(-5;3-;@(,5;A<(5544(:43((4083(&(++9:A@4(4)+((+(:@(4(5&&)05((+(++4:((+(+)(
I have no idea why error occured. Please help. Thank you very much.
Best,
Yang
​

Date: Sat, 18 Jun 2016 16:04:55 -0700

**Comment by lh3** [comment]
Please DON'T use email. Write your message in markdown on this github issue page. The quality string of your first sequence is shorter than reads, but I don't know if it's email that screws up the format. Also use `grep -n -A3 -B4`.
