### ISSUE TITLE
bwa mem 0.7.13-r1126: fix ARGV parsing not to choke on quoted empty strings

### ISSUE THREAD

**Issue by mmokrejs** [lh3/bwa#81]
Seems a quoted empty string upsets ARGV parser.

```
$ bwa mem -t 16 '' -M ref.fasta.gz pairs.fastq | head
[E::bwa_idx_load_from_disk] fail to locate the index files
$

$ bwa mem -t 16 -M ref.fasta.gz pairs.fastq | head
[M::bwa_idx_load_from_disk] read 0 ALT contigs
@SQ     SN:chr1 LN:248956422
@SQ     SN:chr2 LN:242193529
@SQ     SN:chr3 LN:198295559
@SQ     SN:chr4 LN:190214555
@SQ     SN:chr5 LN:181538259
@SQ     SN:chr6 LN:170805979
@SQ     SN:chr7 LN:159345973
@SQ     SN:chr8 LN:145138636
@SQ     SN:chr9 LN:138394717
@SQ     SN:chr10        LN:133797422
$
```

**Comment by lh3** [comment]
That is recognized as the first parameter. It is a misuse.

**Comment by mmokrejs** [comment]
It is unfortunate it is so picky. I believe my case is rather understandable:

```
#! /bin/sh

if [ $q == "$p".pairs.fastq ]; then
    paired="-p"
else
    paired=""

bwa mem -t $threads "$paired" -M -R "@RG\tID:$prefix\tPL:$platform\tLB:$library\tSM:$sample" "$reference" "$q" | samtools view -@ $xthreads -T "$reference" -Sb - > "$s".bam || exit 255
```

**Comment by lh3** [comment]
Try to get rid of double quotation marks here:
```sh
paired=""
```
and here:
```sh
"$paired"
```

**Comment by lh3** [comment]
Note that using `""` will break many unix tools, not just bwa.

**Comment by mmokrejs** [comment]
It is enough to just drop these quotes `"$paired"` from the `bwa` command line itself. It does not matter on the variable definition line.

Well, in general I do place quotes around variables because I newer know if there are multiple words separated by a space or not. Here, it indeed does sound like an overkill but it could have happened elsewhere.

```
$ if $cond; then
    mythreads="-t $threads"
else
    echo "Sticking with defaults"
    mythreads=
fi

# in the case of $mythreads being empty:
$ bwa mem "$mythreads" ...
[E::bwa_idx_load_from_disk] fail to locate the index files
$
```
At least if the error message was not confusing, and included the full path to the index files.

**Comment by lh3** [comment]
No, stop doing this: `"$mythreads"`. This is just wrong. You are abusing quotation marks, which will not only break bwa, but also most of unix tools.
