### ISSUE TITLE
bwa-0.7.13-r1126: calculate proper NM:i tag for reads contain N's

### ISSUE THREAD

**Issue by mmokrejs** [lh3/bwa#82]
Hi,
  `samtools calmd` often outputs a warning like this:

`[bam_fillmd1] different NM for read 'HWI-xxxxx:xxx:xxxxxxxxx:2:1101:1110:65038': 0 -> 1`

  Per discussion at https://sourceforge.net/p/samtools/mailman/samtools-help/thread/8aaa2f1f-c31e-47c0-5e89-6fe10990c847%40gmail.com/#msg35256271 it turns out bwa could do better and calculate NM: tag not using the randomly modified sequence with N's replaced to any nucleotide, but increasing the NM: value by number of N's originally present in the aligned region. Is that possible? In turn, `"samtools calmd"` would issue less warnings, and one could focus on real inconsistencies. Thank you.

**Comment by lh3** [comment]
This won't get fixed. It is not worth the computing time and code complexity.
