### ISSUE TITLE
bwa samse failed 

### ISSUE THREAD

**Issue by danshu** [lh3/bwa#93]
Hi,

I failed to run 
"bwa samse -n 1 ./p_ctg_formated.fa ./read.sai - | grep '\(^@\|XT:A:U\)' | samtools view -S -h -b -F 0x4 - | samtools sort -T ./ -@ 20 -no - ./temporarySam > ./san_fct3_5k.map". 
The error message is " [E::hts_open_format] fail to open file './temporarySam'
[bam_sort_core] fail to open './temporarySam': No such file or directory
[bam_sort] Note the <out.prefix> argument has been replaced by -T/-o options
[gzread] Bad file descriptor"
Anyone can help?

Thanks,
Quan

**Comment by lh3** [comment]
Don't use long pipes if you are debugging. In fact, your grep command is probably wrong. Separate and then test.
