### ISSUE TITLE
Output for unmapped pair 

### ISSUE THREAD

**Issue by readbio** [lh3/bwa#99]
Hi,

I have a pair of read. The first reads can be mapped. The second one can NOT be mapped. 

Here is the mapping results: 
```
@PG     ID:bwa  PN:bwa  VN:0.7.15-r1140 CL:bwa mem ../../results/simu_TEP_ara/tair10.fa test_1read_R1.fq.gz test_1read_R2.fq.gz
chr1_8301745_8302017_2:0:0_1:0:0_0      121     chr1    8296984 60      100M    =       8296984 0       TTTAGGCCCAATAAGGATAATTTGAAACCCACCCCAAAATTTAAACAGAGATGGTTGGATTATGGGCACAAGGTTCCAATTGCTAGATAGCTAAAATTTT        2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222        NM:i:1  MD:Z:95C4       AS:i:95     XS:i:0
chr1_8301745_8302017_2:0:0_1:0:0_0      181     chr1    8296984 0       *       =       8296984 0       GGATTTACTATTTGATCGATACTGCTTTGAACCCCAAATCAAACTGTGAGTTGAACAAATGGATTTACTATTTGATCGATACTGCTTTGAACCCCAAATC        2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222        AS:i:0  XS:i:0
```

In the second line, the summary of the FLAG is:
Summary:
    read paired
    mate unmapped
    read reverse strand
    mate reverse strand
    first in pair

My question is why the seventh line is "=" rather than "*". Does this mean that if I want to check whether the mate is mapped or not, I can NOT just select the seventh with "*" and need to extract based on FLAG? 

Best,
Shaojun Xie

**Comment by lh3** [comment]
This is a SAM question, not a BWA question. Anyway, checking FLAG is the only reliable way.

**Comment by ftian9** [comment]
The reference name of the mate is "=" because it is a hard-coded rule.
If the mate is unmapped, the 7th column will always be "=".
For bwa aln/sampe, the relevant codes are here:
https://github.com/lh3/bwa/blob/master/bwase.c#L433
